import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '2.1.1:17',
  releaseNotes: {
    en_US: `Rebuilt on start-sdk 2.0, with fixes to how Fulcrum reaches its node.

The node is now reached over the internal host bridge rather than the retired .startos hostnames, so Fulcrum finds it reliably and follows it when its port moves. Selecting Flowee now works: Flowee never gave out the password Fulcrum was trying to log in with, so a credential is minted here and registered on Flowee instead. Bitcoin Cash Daemon is reached through its plaintext proxy, which fixes connecting to it on every chain but mainnet. The Knuth option, which no package provides, is gone. Fulcrum's index is no longer copied into backups — it is rebuilt from the node on restore — and deleting the index for one chain is now immediate rather than waiting for a restart. Fulcrum also no longer waits for the node to finish syncing before it will start: it indexes to whatever height the node has reached and follows it from there, so its own progress is visible from the first block.`,
    es_ES: `Reconstruido sobre start-sdk 2.0, con correcciones en la forma en que Fulcrum accede a su nodo.

El nodo ahora se localiza a través del puente interno del sistema en lugar de los nombres .startos retirados, de modo que Fulcrum lo encuentra de forma fiable y lo sigue cuando cambia de puerto. Seleccionar Flowee ya funciona: Flowee nunca entregaba la contraseña con la que Fulcrum intentaba iniciar sesión, así que ahora la credencial se genera aquí y se registra en Flowee. Bitcoin Cash Daemon se alcanza mediante su proxy en texto plano, lo que corrige la conexión en todas las cadenas salvo mainnet. La opción Knuth, que ningún paquete proporciona, ha desaparecido. El índice de Fulcrum ya no se copia en las copias de seguridad —se reconstruye desde el nodo al restaurar— y eliminar el índice de una cadena es ahora inmediato en lugar de esperar a un reinicio. Fulcrum tampoco espera ya a que el nodo termine de sincronizarse para arrancar: indexa hasta la altura que el nodo haya alcanzado y lo sigue desde ahí, de modo que su propio progreso es visible desde el primer bloque.`,
    de_DE: `Neu gebaut auf start-sdk 2.0, mit Korrekturen daran, wie Fulcrum seinen Knoten erreicht.

Der Knoten wird jetzt über die interne Host-Bridge statt über die abgeschafften .startos-Namen erreicht, sodass Fulcrum ihn zuverlässig findet und ihm folgt, wenn sich sein Port ändert. Die Auswahl von Flowee funktioniert nun: Flowee gab das Passwort, mit dem Fulcrum sich anmelden wollte, nie heraus — die Zugangsberechtigung wird jetzt hier erzeugt und auf Flowee registriert. Bitcoin Cash Daemon wird über seinen Klartext-Proxy erreicht, was die Verbindung auf allen Chains außer Mainnet repariert. Die Knuth-Option, für die es kein Paket gibt, ist entfallen. Fulcrums Index landet nicht mehr in Backups — er wird beim Wiederherstellen aus dem Knoten neu aufgebaut — und das Löschen des Index einer Chain wirkt jetzt sofort statt erst nach einem Neustart. Fulcrum wartet außerdem nicht mehr darauf, dass der Knoten fertig synchronisiert ist: Es indiziert bis zu der Höhe, die der Knoten erreicht hat, und folgt ihm von dort, sodass sein eigener Fortschritt ab dem ersten Block sichtbar ist.`,
    pl_PL: `Przebudowano na start-sdk 2.0, wraz z poprawkami sposobu, w jaki Fulcrum łączy się ze swoim węzłem.

Węzeł jest teraz osiągany przez wewnętrzny mostek systemu zamiast wycofanych nazw .startos, dzięki czemu Fulcrum znajduje go niezawodnie i podąża za nim, gdy zmieni port. Wybranie Flowee wreszcie działa: Flowee nigdy nie udostępniał hasła, którym Fulcrum próbował się logować, więc dane logowania są teraz tworzone tutaj i rejestrowane we Flowee. Bitcoin Cash Daemon jest osiągany przez jego jawny serwer pośredniczący, co naprawia połączenie we wszystkich łańcuchach poza mainnetem. Opcja Knuth, której żaden pakiet nie zapewnia, została usunięta. Indeks Fulcrum nie trafia już do kopii zapasowych — jest odbudowywany z węzła przy przywracaniu — a usunięcie indeksu jednego łańcucha działa teraz natychmiast, bez czekania na ponowne uruchomienie. Fulcrum nie czeka też już na zakończenie synchronizacji węzła, aby wystartować: indeksuje do wysokości, jaką węzeł osiągnął, i podąża za nim dalej, więc jego własny postęp widać od pierwszego bloku.`,
    fr_FR: `Reconstruit sur start-sdk 2.0, avec des corrections sur la façon dont Fulcrum joint son nœud.

Le nœud est désormais joint via le pont interne de l'hôte plutôt que par les noms .startos retirés, de sorte que Fulcrum le trouve de façon fiable et le suit lorsque son port change. Choisir Flowee fonctionne maintenant : Flowee ne communiquait jamais le mot de passe avec lequel Fulcrum tentait de se connecter, l'identifiant est donc créé ici puis enregistré sur Flowee. Bitcoin Cash Daemon est joint via son proxy en clair, ce qui corrige la connexion sur toutes les chaînes sauf mainnet. L'option Knuth, qu'aucun paquet ne fournit, a disparu. L'index de Fulcrum n'est plus copié dans les sauvegardes — il est reconstruit à partir du nœud lors de la restauration — et la suppression de l'index d'une chaîne prend effet immédiatement au lieu d'attendre un redémarrage. Fulcrum n'attend plus non plus que le nœud ait fini de se synchroniser pour démarrer : il indexe jusqu'à la hauteur atteinte par le nœud et le suit ensuite, si bien que sa propre progression est visible dès le premier bloc.`,
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
